In [6]:
!pip install mysql-connector-python sqlalchemy pymysql
import mysql.connector
try:
    connection = mysql.connector.connect(
        host="localhost",
        user="root",
        password="shobana07!"
    )
    if connection.is_connected():
        print("MySQL connection successful!")
except Exception as e:
    print("Connection failed!")
    print("Error:", e)
finally:
    if 'connection' in locals() and connection.is_connected():
        connection.close()

Requirement already satisfied: mysql-connector-python in c:\users\skris\anaconda3\lib\site-packages (26.7.0)
Requirement already satisfied: sqlalchemy in c:\users\skris\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: pymysql in c:\users\skris\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\skris\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\skris\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
MySQL connection successful!

In [8]:
from sqlalchemy import create_engine
username = "root"
password = "shobana07!"
host = "localhost"
database = "heart_disease_db"
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}/{database}"
)
print("Python connected to heart_disease_db!")

Python connected to heart_disease_db!

In [10]:
import pandas as pd
df = pd.read_csv("C:/Users/skris/Downloads/AI_Healthcare_Heart_Disease/datasets/heart_disease_clean.csv")
print("Dataset loaded!")
print("Shape:", df.shape)
display(df.head())

Dataset loaded!
Shape: (303, 15)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,disease_status
0,63,1,1,145.0,233.0,1,2,150.0,0,2.3,3,0,6,0,No Heart Disease
1,67,1,4,160.0,286.0,0,2,108.0,1,1.5,2,3,3,1,Heart Disease
2,67,1,4,120.0,229.0,0,2,129.0,1,2.6,2,2,7,1,Heart Disease
3,37,1,3,130.0,250.0,0,0,187.0,0,3.5,3,0,3,0,No Heart Disease
4,41,0,2,130.0,204.0,0,2,172.0,0,1.4,1,0,3,0,No Heart Disease

In [12]:
df.to_sql(
    name="heart_patients",
    con=engine,
    if_exists="replace",
    index=False
)
print("Data successfully uploaded to MySQL!")

Data successfully uploaded to MySQL!

In [14]:
query = """
SELECT COUNT(*) AS total_patients
FROM heart_patients;
"""
result = pd.read_sql(query, engine)
display(result)

   total_patients
0             303

In [16]:
query = """
SELECT 
    target,
    COUNT(*) AS patient_count
FROM heart_patients
GROUP BY target
ORDER BY target;
"""
result = pd.read_sql(query, engine)
display(result)

   target  patient_count
0       0            164
1       1            139